### ISSUE TITLE
implement a real database like postgres

### ISSUE THREAD

**Issue by Donmmi** [quii/learn-go-with-tests#155] opened 2019-02-15 05:43 UTC
Hi, 
    I am lost in how to implement postgres with test, I have read and write "Build an application" multi times and want to write a postgresql store, but I don't know how to  easily create  initialization data and clean them，should I use  insert to create init data then clean them after test? I want to know if there is a more elegant way to test the real database. 

    Thanks lot!

**Comment by quii** [comment] 2019-02-15 09:24
One day I may get around to it, but that doesn't help you right now so here's a few thoughts

Use docker-compose to spin up a real, clean postgres for your tests. That way you can always start from scratch and gives you the opportunity to test your database migrations work (e.g the things that create your tables).

**Comment by Donmmi** [comment] 2019-02-18 01:38
@quii Thanks very much! Expecting your new article! :)

**Comment by Donmmi** [comment] 2019-02-28 06:10
I found a sql mock library: github.com/DATA-DOG/go-sqlmock, It can fulfill my request. Maybe someone need this too :)

**Comment by quii** [comment] 2019-07-11 16:11
Duplicate of #103

**Closed by quii** 2019-07-11 16:11 UTC
