### ISSUE TITLE
Atomics and mutexes

### ISSUE THREAD

**Issue by enkeyz** [quii/learn-go-with-tests#562] opened 2022-04-24 09:22 UTC
Atomic package also could be mentioned in the Sync chapter, which provides an alternative to mutexes.

https://pkg.go.dev/sync/atomic

(Looks like there's already an open issue about it https://github.com/quii/learn-go-with-tests/issues/307 )

**Comment by quii** [comment] 2024-06-21 14:02
Dupe of #307

**Closed by quii** 2024-06-21 14:02 UTC
